### ISSUE TITLE
emoji-keyboard opens locally and on remote with fullscreen remote desktop session

### ISSUE THREAD

**Issue by robertwidfen** [gilleswaeber/emoji-keyboard#17]
This is likely not really an emoji-keyboard issue, but it is AHK related. The hotkeys are processed on the local and remote host when running RDP in full screen. Both of my machines run Windows 10.

I wrapped the KB.toggle() in "If WinActive("ahk_class TscShellContainerClass")  {KB.toggle()}" to avoid this.

**Comment by gilleswaeber** [comment]
I'm not using RDP, but that should definitely get fixed. I tried it with the solutions I'm regulary using:
- TeamViewer: only executed on the local host, works (most of the time) since the clipboard is shared
- Moonlight: the keyboard appears on the local host, the remote host only receives Ctrl+V

The best solution here might be to use HotIf to disable the hotkey if any is detected

Changing the hotkey might also affect the behavior. I've been thinking of moving the hotkey to a separate file to make changes to it easier, might then be fixed together

**Comment by robertwidfen** [comment]
Having different ones actually solves the problem, but interferes with my muscle memory 😇.

"moving the hotkey to a separate file" is a good idea, the actual key is more like a user-config and I could have the detection above in the user config file and keep the core untouched ...

I really want to keep it running on both - one of the machines I use by RDP (when in home office) and locally (when in office) ...

**Comment by gilleswaeber** [comment]
Hi, this is finally fixed with the latest version. Don't hesitate to report anything else you might encounter 😼
