### ISSUE TITLE
How about a search function?

### ISSUE THREAD

**Issue by benshep** [gilleswaeber/emoji-keyboard#2]
Often I know which emoji I want - a search function would be nice, perhaps using TAB or another currently unused key.

**Comment by romligCH** [comment]
The emoji names and keywords are already loaded in the script. So that part is already ok. But there are no keywords like `:)`, `:(`, etc.

What about a passive search function mode, similar to smartphones keyboard (e.g. Swiftkey):
- the script read each key you type but doesn't intercept it
- suggestions are shown for the word you are currently typing
- you can insert an emoji while typing by clicking on its icon or with a shortcut (e.g. numpad keys or ctrl+number)
- if you insert an emoji before you finished the word, the backspace key is sent multiple time to erase the already typed letters
- if you press the spacebar or enter or an arrow, etc. the last suggestions are shown until enter a new letter, the backspace key is not sent if you insert an emoji

**Comment by benshep** [comment]
Hmm, I think I would rather search "within the app" than have it monitoring all my keystrokes. I'm not paranoid but I don't want the performance hit for something I'm not using all that often.
