### ISSUE TITLE
Didn't get how to add/change emoji

### ISSUE THREAD

**Issue by j2l** [gilleswaeber/emoji-keyboard#6]
It's a doc issue or I'm dumb 😄

**Comment by gilleswaeber** [comment]
This is currently not clearly documented. I will try to improve that in the future.

The support for arbitrarily changing emojis is limited. The `wwwassets/scripts/data.js` file contains the full layout configuration.

This file is generated by the PHP scripts in the `res` folder (PHP is used because it doesn't require any additional dependency for these small scripts).

The `config.json` file defines how the file is generated, see `config.schema.json` for the exact layout.

The image files (svg) are stored in `wwwassets/img`. They are copied from the twemoji repo. They are used in function of the defined fallback rules.

Now, concretely:
- To update to a newer emoji version, update the numbers in forceVersion or remove the section to use the latest version (iirc, launching the build script will show you the latest versions)
- To add an arbitrary emoji, add it in the addon section, the group+subgroup pair must be present somewhere in the keyboards list otherwise you won't see it
- To remove a subgroup, remove it in the keyboards section
- Eventually, you will have to update the fallback rules and add newer twemoji images

After that, you have to rebuild the data file, see the README in the res folder.

**Comment by j2l** [comment]
Thank you!
I'll do that tomorrow.
