### ISSUE TITLE
How to add other unicode characters and personal SVG?

### ISSUE THREAD

**Issue by j2l** [gilleswaeber/emoji-keyboard#7]
Bonjour Gilles,
I need to change unicode characters beyond emoji, like [Unified Canadian Aboriginal Syllabics 1400—167F](https://unicode-table.com/en/blocks/unified-canadian-aboriginal-syllabics/), and I also need to add my own SVG for non existing unicode.
For the first part, I guess we can, but how?
For the second part, I really wonder. Does SVG can now be passed through typed keys, like the clipboard?
Merci

**Comment by gilleswaeber** [comment]
Bonjour,
the first is definitely possible. It was already possible with the previous versions but I suggest you upgrade to the latest because it is easier now. I also added a few examples on how to do it.

One thing to keep in mind is that there is a limit of 408 symbols on each keyboard, 12 pages of 34, excluding alternates. Note for alternates: if there are two, it considers it a lowercase/uppercase tuple and if there are more, it will use the same system as for the skins.
One possible solution would be, in config.json, to add
```json
{"group": "Canadian Aboriginal Syllabics", "subGroup": "base-a", "symbols": [{"from": "᐀", "to": "ᖖ"}]},
{"group": "Canadian Aboriginal Syllabics", "subGroup": "base-b", "symbols": [{"from": "ᖗ", "to": "ᙿ"}]},
{"group": "Canadian Aboriginal Syllabics", "subGroup": "extended", "symbols": [{"from": "ᢰ", "to": "ᣵ"}]}
```
in addons and
```
{"name":"UCAS-1", "symbol":"ᐁ", "content":[
	{"group":"Canadian Aboriginal Syllabics", "subGroup":"base-a"}
]},{"name":"UCAS-2", "symbol":"ᖗ", "content":[
	{"group":"Canadian Aboriginal Syllabics", "subGroup":"base-b"},
	{"group":"Canadian Aboriginal Syllabics", "subGroup":"extended"}
]}
```
in keyboards (add commas where needed).

I have compiled a data.js file with these settings: [data.js.zip](https://github.com/gilleswaeber/emoji-keyboard/files/1798404/data.js.zip). You can drop it in the `wwwassets\script` folder.

I did simply split the set in two so that it would fit on a paged keyboard, but there is certainly a more appropriated layout. I would be interested if you get something better. I am not familiar with these languages and I found no obvious grouping.

For your second question, it is certainly possible but I don't think that would you help you much. The support for SVG is still, sadly, quite limited (last time I have tried, you could not even paste SVGs into Word).

If it is for characters, I would recommend first mapping them to codepoints in the unicode Private Use Area and creating a font with your images. The [Icomoon App](https://icomoon.io/) can help you with that. See also the [Medieval Unicode Font Initiative](http://folk.uib.no/hnooh/mufi/).

If your SVGs are images, you may prefer to use EMF vector files for MS Office compatibility.

Also, behind the scenes, the keyboard is actually using the clipboard. It saves the clipboard, overwrites it with the symbol, paste, and then restores it. I tried multiple solutions and I found this one to be the most reliable.

En espérant que cela aide.

**Comment by j2l** [comment]
Merci, ça aide beaucoup !
C'est drôle, j'étais justement sur IcoMoon et la PUA Unicode.
Je préfère l'approche de ce projet que de faire une police de caractère (ce que j'ai déjà fait avec FontForge), car on peut aller en profondeur à partir d'un simple clavier (dommage que AHK n'existe pas sur Mac et Linux).
Est ce que la version html pourrait aussi être utilisé pour une textarea ?

Hier, j'ai déjà réalisé 110 SVG à mapper et j'en aurais bien plus par la suite.

**Comment by j2l** [comment]
Looks like the source is borken:
```
Could not connect to unicode website.
Please check that ftp support is enabled and that http://www.unicode.org/Public/cldr/0/core.zip exists and try again.
```

**Comment by gilleswaeber** [comment]
Pas de problème avec la source mais un problème avec le code du builder, corrigé dans b1c3417daf80422fc88c61dfa6cbcbe7fdb5a4ac.

Il doit être possible d'intégrer le code sur un site web relativement facilement. Le code est même déjà compatible avec Internet Explorer (nécessaire pour AHK). On peut aussi envisager une Web Extension, mais cela n'est pas une priorité pour moi en ce moment.

Le plus gros problème avec Linux serait au niveau du keyboard hook. Soit on a un code bas-niveau, mais qui nécessite le root, ce qui n'est pas génial niveau sécurité, soit on a un code qui intéragit avec le serveur X, ce qui demande plusieurs implémenations différentes et il semble que ce mode soit parfois même désactivé. Je ne connais pas assez Mac pour me prononcer.

**Comment by j2l** [comment]
Merci et excellente journée,
Je vais essayer tout ça.
